---
kind: pipeline
type: docker
name: rfactor

environment:
  CONDA_ACTIVATE: /opt/conda/bin/activate
steps:

  - name: environment
    image: continuumio/miniconda3
    commands:
      - conda env create -p ./env -f environment.yml
      - . $CONDA_ACTIVATE
      - conda activate /src/rfactor/env
      - pip install -e .[develop]

  - name: install
    image: continuumio/miniconda3
    commands:
      - . $CONDA_ACTIVATE
      - conda activate /src/rfactor/env
      - python setup.py develop --no-deps

  - name: unit-tests
    image: continuumio/miniconda3
    commands:
      - . $CONDA_ACTIVATE
      - conda activate /src/rfactor/env
      - pytest tests/ -m "not externaldepedent"

  - name: documentation
    image: continuumio/miniconda3
    commands:
      - . $CONDA_ACTIVATE
      - conda activate /src/rfactor/env
      - conda install -c conda-forge pandoc
      - python setup.py build_sphinx -s docs

  - name: publish
    image: plugins/gh-pages
    settings:
      username: johanvdw
      password:
        from_secret: gh-pages-release
      pages_directory: docs/_build/html/
    when:
      branch:
        - master
      event:
         exclude:
           - pull_request

workspace:
  base: /src
  path: rfactor
